/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Cidade service. Represents a row in the &quot;Cidade&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.services.model.impl.CidadeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.services.model.impl.CidadeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Cidade
 * @generated
 */
@ProviderType
public interface CidadeModel extends BaseModel<Cidade> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cidade model instance should use the {@link Cidade} interface instead.
	 */

	/**
	 * Returns the primary key of this cidade.
	 *
	 * @return the primary key of this cidade
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cidade.
	 *
	 * @param primaryKey the primary key of this cidade
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cidade ID of this cidade.
	 *
	 * @return the cidade ID of this cidade
	 */
	public long getCidadeId();

	/**
	 * Sets the cidade ID of this cidade.
	 *
	 * @param cidadeId the cidade ID of this cidade
	 */
	public void setCidadeId(long cidadeId);

	/**
	 * Returns the nome of this cidade.
	 *
	 * @return the nome of this cidade
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this cidade.
	 *
	 * @param nome the nome of this cidade
	 */
	public void setNome(String nome);

	/**
	 * Returns the estado ID of this cidade.
	 *
	 * @return the estado ID of this cidade
	 */
	public long getEstadoId();

	/**
	 * Sets the estado ID of this cidade.
	 *
	 * @param estadoId the estado ID of this cidade
	 */
	public void setEstadoId(long estadoId);

}