/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.services.model.Cidade;
import com.services.model.CidadeModel;
import com.services.model.CidadeSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Cidade service. Represents a row in the &quot;Cidade&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CidadeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CidadeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CidadeImpl
 * @generated
 */
@JSON(strict = true)
public class CidadeModelImpl
	extends BaseModelImpl<Cidade> implements CidadeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cidade model instance should use the <code>Cidade</code> interface instead.
	 */
	public static final String TABLE_NAME = "Cidade";

	public static final Object[][] TABLE_COLUMNS = {
		{"cidadeId", Types.BIGINT}, {"nome", Types.VARCHAR},
		{"estadoId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("cidadeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("estadoId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Cidade (cidadeId LONG not null primary key,nome VARCHAR(75) null,estadoId LONG)";

	public static final String TABLE_SQL_DROP = "drop table Cidade";

	public static final String ORDER_BY_JPQL = " ORDER BY cidade.cidadeId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY Cidade.cidadeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ESTADOID_COLUMN_BITMASK = 1L;

	public static final long CIDADEID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Cidade toModel(CidadeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Cidade model = new CidadeImpl();

		model.setCidadeId(soapModel.getCidadeId());
		model.setNome(soapModel.getNome());
		model.setEstadoId(soapModel.getEstadoId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Cidade> toModels(CidadeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Cidade> models = new ArrayList<Cidade>(soapModels.length);

		for (CidadeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public CidadeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cidadeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCidadeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cidadeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Cidade.class;
	}

	@Override
	public String getModelClassName() {
		return Cidade.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Cidade, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Cidade, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Cidade, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Cidade)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Cidade, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Cidade, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Cidade)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Cidade, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Cidade, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Cidade>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Cidade.class.getClassLoader(), Cidade.class, ModelWrapper.class);

		try {
			Constructor<Cidade> constructor =
				(Constructor<Cidade>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Cidade, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Cidade, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Cidade, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Cidade, Object>>();
		Map<String, BiConsumer<Cidade, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Cidade, ?>>();

		attributeGetterFunctions.put("cidadeId", Cidade::getCidadeId);
		attributeSetterBiConsumers.put(
			"cidadeId", (BiConsumer<Cidade, Long>)Cidade::setCidadeId);
		attributeGetterFunctions.put("nome", Cidade::getNome);
		attributeSetterBiConsumers.put(
			"nome", (BiConsumer<Cidade, String>)Cidade::setNome);
		attributeGetterFunctions.put("estadoId", Cidade::getEstadoId);
		attributeSetterBiConsumers.put(
			"estadoId", (BiConsumer<Cidade, Long>)Cidade::setEstadoId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getCidadeId() {
		return _cidadeId;
	}

	@Override
	public void setCidadeId(long cidadeId) {
		_cidadeId = cidadeId;
	}

	@JSON
	@Override
	public String getNome() {
		if (_nome == null) {
			return "";
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		_nome = nome;
	}

	@JSON
	@Override
	public long getEstadoId() {
		return _estadoId;
	}

	@Override
	public void setEstadoId(long estadoId) {
		_columnBitmask |= ESTADOID_COLUMN_BITMASK;

		if (!_setOriginalEstadoId) {
			_setOriginalEstadoId = true;

			_originalEstadoId = _estadoId;
		}

		_estadoId = estadoId;
	}

	public long getOriginalEstadoId() {
		return _originalEstadoId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Cidade.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Cidade toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Cidade>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CidadeImpl cidadeImpl = new CidadeImpl();

		cidadeImpl.setCidadeId(getCidadeId());
		cidadeImpl.setNome(getNome());
		cidadeImpl.setEstadoId(getEstadoId());

		cidadeImpl.resetOriginalValues();

		return cidadeImpl;
	}

	@Override
	public int compareTo(Cidade cidade) {
		long primaryKey = cidade.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Cidade)) {
			return false;
		}

		Cidade cidade = (Cidade)object;

		long primaryKey = cidade.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalEstadoId = _estadoId;

		_setOriginalEstadoId = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Cidade> toCacheModel() {
		CidadeCacheModel cidadeCacheModel = new CidadeCacheModel();

		cidadeCacheModel.cidadeId = getCidadeId();

		cidadeCacheModel.nome = getNome();

		String nome = cidadeCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			cidadeCacheModel.nome = null;
		}

		cidadeCacheModel.estadoId = getEstadoId();

		return cidadeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Cidade, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Cidade, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Cidade, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Cidade)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Cidade, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Cidade, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Cidade, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Cidade)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Cidade>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _cidadeId;
	private String _nome;
	private long _estadoId;
	private long _originalEstadoId;
	private boolean _setOriginalEstadoId;
	private long _columnBitmask;
	private Cidade _escapedModel;

}