/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.services.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.services.model.Contato;
import com.services.model.ContatoModel;
import com.services.model.ContatoSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Contato service. Represents a row in the &quot;Contato&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ContatoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContatoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContatoImpl
 * @generated
 */
@JSON(strict = true)
public class ContatoModelImpl
	extends BaseModelImpl<Contato> implements ContatoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contato model instance should use the <code>Contato</code> interface instead.
	 */
	public static final String TABLE_NAME = "Contato";

	public static final Object[][] TABLE_COLUMNS = {
		{"contatoId", Types.BIGINT}, {"nome", Types.VARCHAR},
		{"email", Types.VARCHAR}, {"telefone", Types.VARCHAR},
		{"Mensagem", Types.VARCHAR}, {"cidadeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("contatoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("telefone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Mensagem", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cidadeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Contato (contatoId LONG not null primary key,nome VARCHAR(75) null,email VARCHAR(75) null,telefone VARCHAR(75) null,Mensagem VARCHAR(75) null,cidadeId LONG)";

	public static final String TABLE_SQL_DROP = "drop table Contato";

	public static final String ORDER_BY_JPQL =
		" ORDER BY contato.contatoId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY Contato.contatoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Contato toModel(ContatoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Contato model = new ContatoImpl();

		model.setContatoId(soapModel.getContatoId());
		model.setNome(soapModel.getNome());
		model.setEmail(soapModel.getEmail());
		model.setTelefone(soapModel.getTelefone());
		model.setMensagem(soapModel.getMensagem());
		model.setCidadeId(soapModel.getCidadeId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Contato> toModels(ContatoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Contato> models = new ArrayList<Contato>(soapModels.length);

		for (ContatoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ContatoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _contatoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setContatoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _contatoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Contato.class;
	}

	@Override
	public String getModelClassName() {
		return Contato.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Contato, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Contato, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Contato, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Contato)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Contato, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Contato, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Contato)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Contato, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Contato, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Contato>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Contato.class.getClassLoader(), Contato.class, ModelWrapper.class);

		try {
			Constructor<Contato> constructor =
				(Constructor<Contato>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Contato, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Contato, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Contato, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Contato, Object>>();
		Map<String, BiConsumer<Contato, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Contato, ?>>();

		attributeGetterFunctions.put("contatoId", Contato::getContatoId);
		attributeSetterBiConsumers.put(
			"contatoId", (BiConsumer<Contato, Long>)Contato::setContatoId);
		attributeGetterFunctions.put("nome", Contato::getNome);
		attributeSetterBiConsumers.put(
			"nome", (BiConsumer<Contato, String>)Contato::setNome);
		attributeGetterFunctions.put("email", Contato::getEmail);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<Contato, String>)Contato::setEmail);
		attributeGetterFunctions.put("telefone", Contato::getTelefone);
		attributeSetterBiConsumers.put(
			"telefone", (BiConsumer<Contato, String>)Contato::setTelefone);
		attributeGetterFunctions.put("Mensagem", Contato::getMensagem);
		attributeSetterBiConsumers.put(
			"Mensagem", (BiConsumer<Contato, String>)Contato::setMensagem);
		attributeGetterFunctions.put("cidadeId", Contato::getCidadeId);
		attributeSetterBiConsumers.put(
			"cidadeId", (BiConsumer<Contato, Long>)Contato::setCidadeId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getContatoId() {
		return _contatoId;
	}

	@Override
	public void setContatoId(long contatoId) {
		_contatoId = contatoId;
	}

	@JSON
	@Override
	public String getNome() {
		if (_nome == null) {
			return "";
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		_nome = nome;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@JSON
	@Override
	public String getTelefone() {
		if (_telefone == null) {
			return "";
		}
		else {
			return _telefone;
		}
	}

	@Override
	public void setTelefone(String telefone) {
		_telefone = telefone;
	}

	@JSON
	@Override
	public String getMensagem() {
		if (_Mensagem == null) {
			return "";
		}
		else {
			return _Mensagem;
		}
	}

	@Override
	public void setMensagem(String Mensagem) {
		_Mensagem = Mensagem;
	}

	@JSON
	@Override
	public long getCidadeId() {
		return _cidadeId;
	}

	@Override
	public void setCidadeId(long cidadeId) {
		_cidadeId = cidadeId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Contato.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Contato toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Contato>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContatoImpl contatoImpl = new ContatoImpl();

		contatoImpl.setContatoId(getContatoId());
		contatoImpl.setNome(getNome());
		contatoImpl.setEmail(getEmail());
		contatoImpl.setTelefone(getTelefone());
		contatoImpl.setMensagem(getMensagem());
		contatoImpl.setCidadeId(getCidadeId());

		contatoImpl.resetOriginalValues();

		return contatoImpl;
	}

	@Override
	public int compareTo(Contato contato) {
		long primaryKey = contato.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Contato)) {
			return false;
		}

		Contato contato = (Contato)object;

		long primaryKey = contato.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Contato> toCacheModel() {
		ContatoCacheModel contatoCacheModel = new ContatoCacheModel();

		contatoCacheModel.contatoId = getContatoId();

		contatoCacheModel.nome = getNome();

		String nome = contatoCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			contatoCacheModel.nome = null;
		}

		contatoCacheModel.email = getEmail();

		String email = contatoCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			contatoCacheModel.email = null;
		}

		contatoCacheModel.telefone = getTelefone();

		String telefone = contatoCacheModel.telefone;

		if ((telefone != null) && (telefone.length() == 0)) {
			contatoCacheModel.telefone = null;
		}

		contatoCacheModel.Mensagem = getMensagem();

		String Mensagem = contatoCacheModel.Mensagem;

		if ((Mensagem != null) && (Mensagem.length() == 0)) {
			contatoCacheModel.Mensagem = null;
		}

		contatoCacheModel.cidadeId = getCidadeId();

		return contatoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Contato, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Contato, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Contato, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Contato)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Contato, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Contato, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Contato, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Contato)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Contato>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _contatoId;
	private String _nome;
	private String _email;
	private String _telefone;
	private String _Mensagem;
	private long _cidadeId;
	private Contato _escapedModel;

}